# Generated by Django 5.0.3 on 2024-03-19 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('senha', models.CharField(max_length=50)),
                ('genero', models.CharField(max_length=11)),
                ('dataNascimento', models.DateField()),
                ('telefone', models.CharField(max_length=15)),
            ],
        ),
    ]
