# Generated by Django 5.0.3 on 2024-03-20 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0002_alter_usuario_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='id',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='email',
            field=models.EmailField(editable=False, max_length=254, primary_key=True, serialize=False),
        ),
    ]
